# Generated by Django 5.0.2 on 2024-03-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('productname', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=12)),
                ('secondaryPhonenumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
    ]
