# Generated by Django 5.0.2 on 2024-03-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0002_salesorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coustmername', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('secondaryphonenumber', models.CharField(max_length=50)),
                ('productname', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('deliveryaddress', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
