# Generated by Django 5.0.2 on 2024-03-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0003_salesdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=70)),
                ('prod_img', models.ImageField(upload_to='products/pics')),
                ('prod_quantity', models.CharField(max_length=20)),
                ('prod_price', models.IntegerField()),
                ('prod_colour', models.CharField(max_length=20)),
            ],
        ),
    ]
