# Generated by Django 5.0.2 on 2024-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0004_productsdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdetails',
            name='prod_img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
